/**
 * Per-app privacy facts.
 *
 * Every entry was derived from the app's `manifest.yml` and source — declared scopes,
 * `permissions.external.fetch`, whether `@forge/llm` is actually used, the storage keys
 * written, and the Forge SQL schema — not from marketing copy. When an app stores a
 * credential, it says so.
 */

export interface PrivacyFacts {
  /** URL segment, matching the documentation slug. */
  slug: string;
  name: string;
  products: string;
  icon: string;
  summary: string;
  /** True only when the app really calls Forge LLM. */
  ai: boolean;
  /** What a prompt contains. Required when `ai` is true. */
  aiData?: string[];
  persisted: string[];
  transient: string[];
  personal: string[];
  scopes: string[];
  storageTech: string;
  /** Outbound hosts the manifest declares; empty means none. */
  external: string[];
}

export const UPDATED = "28 August 2026";
export const VENDOR = "SynapseOasis";
export const CONTACT_EMAIL = "support@synapseoasis.com";
export const SUPPORT_PORTAL = "https://synapseoasis.atlassian.net/servicedesk/customer/portals";

export const PRIVACY_FACTS: PrivacyFacts[] = [
  {
    slug: "ai-portal-chat",
    name: "AI Portal Chat for JSM",
    products: "Jira Service Management",
    icon: "/ai-portal.png",
    summary:
      "AI Portal Chat for JSM is an AI assistant for the Jira Service Management customer portal. It answers customer questions, searches your knowledge base, and creates or updates requests from the conversation.",
    ai: true,
    aiData: [
      "the customer's chat messages and the history of the current conversation",
      "request type names, field names and descriptions of the service desks the assistant is allowed to use",
      "excerpts of Confluence pages and knowledge base articles returned by the search the assistant runs on the customer's behalf",
      "the global, service-desk and request-type instructions written by your administrators, and any active operational notice",
    ],
    persisted: [
      "**Service desk and request type configuration** — which desks and request types the assistant may use, whether knowledge base search is enabled and for which Confluence spaces, auto-confirm behaviour, and the instructions written by your administrators.",
      "**Conversations** — the messages exchanged in a chat session, its status, the service desks and Confluence spaces the session was allowed to search, timestamps, and the thumbs up or down a customer may leave.",
      "**Branding** — the trigger layout, colours, avatar name and the avatar image you upload.",
      "**An API token** generated by the app, used to authenticate calls to its web trigger for managing operational notices. It is shown once and can be regenerated at any time.",
      "**Usage statistics** — daily counters such as conversations, requests created and deflections, for the admin dashboard.",
      "**Audit entries** — a record of the automated actions the app performed, with timestamps.",
      "**Per-issue AI results** — the classification or suggestion produced for a request, stored against the issue key.",
      "**Agent skill profiles** — a per-agent skill summary derived from previously handled requests, stored against the Atlassian account ID.",
    ],
    transient: [
      "portal requests, issue fields, comments and request type metadata read from Jira Service Management",
      "Confluence and knowledge base search results, limited to the spaces configured for that desk",
      "files a customer attaches during a conversation, which are passed to Jira as request attachments",
      "user, customer and group lookups from Jira",
    ],
    personal: [
      "**Chat messages are stored as written.** If a customer types personal data into the chat, that text is retained in the conversation record until the conversation is deleted or the app is uninstalled.",
      "Atlassian account IDs are stored when the app records an agent skill profile, an audit entry, or an action it performed on a request. They are the identifiers Atlassian itself uses and are meaningless outside your tenant.",
      "Attachments are not retained by the app: they are uploaded to the Jira request and then follow that issue.",
      "Once a day the app sends Atlassian the account IDs it holds, through Atlassian's **Personal Data Reporting** API, and Atlassian answers with the accounts that have been closed. Nothing else tells an app that a person left. Both stores are read and both are erased: in the key-value store a closed account's skill profile and the records keyed on it are removed, and in the audit table its rows are **deleted** — the row itself, not just the name on it, because an audit row carries an open metadata record about what happened.",
      "The app does not collect passwords, end-user credentials or payment data.",
    ],
    scopes: [
      "read:servicedesk-request",
      "write:servicedesk-request",
      "manage:servicedesk-customer",
      "read:jira-user",
      "read:jira-work",
      "write:jira-work",
      "search:confluence",
      "read:space:confluence",
      "storage:app",
      "report:personal-data",
    ],
    storageTech:
      "Forge app storage (key-value store) and Forge SQL, both hosted by Atlassian",
    external: ["`api.atlassian.com` — the Atlassian REST APIs of your own site"],
  },

  {
    slug: "ai-triage",
    name: "AI Triage for JSM",
    products: "Jira Service Management · Jira",
    icon: "/ai-triage.png",
    summary:
      "AI Triage for JSM routes incoming tickets automatically. The Dispatcher Agent assigns the right team or agent, Smart Escalation raises priority based on request content and sentiment, and Incident Detection clusters similar reports in real time.",
    ai: true,
    aiData: [
      "the summary, description, comments and selected field values of the issue being triaged",
      "the candidate teams, members, request types and priorities the agent may choose from, with the routing prompts your administrators wrote",
      "the dispatch, escalation or clustering instructions configured for that service desk",
    ],
    persisted: [
      "**Rule configuration** — dispatcher, escalation and incident detection settings per service desk and per request type, including the thresholds, actions, escalation users and clustering parameters.",
      "**Atlassian Teams connection** — when team-based routing is used: the administrator email, the organisation ID and the **Atlassian API token** supplied for reading Atlassian Teams. The token is masked in the interface.",
      "**Per-issue AI results** — the routing decision, the sentiment or escalation assessment, and the incident grouping produced for an issue, stored against the issue key.",
      "**Audit entries** — what the app decided and did, with timestamps, so administrators can review automated actions.",
      "**Usage statistics** — daily counters for triage and escalation volumes.",
      "**Agent skill profiles** — the skill text an agent writes about themselves, or an administrator writes about them, stored against the Atlassian account ID.",
      "**Scan checkpoints** — the timestamp of the last incident detection scan per service desk.",
    ],
    transient: [
      "issues, comments, change history and field values read from Jira",
      "request type and service desk metadata",
      "Atlassian Teams and team membership, when the Teams connection is configured",
      "user and group lookups from Jira",
    ],
    personal: [
      "Atlassian account IDs are stored in agent skill profiles, audit entries and routing decisions.",
      "Issue and comment text is read to make a decision. The stored result keeps the decision and a short justification, not a copy of the issue.",
      "The **Atlassian API token** used for the Teams connection is a credential you provide, stored inside your own tenant. Create it for this purpose and rotate it on your usual schedule.",
      "Once a day the app sends Atlassian the account IDs it holds, through Atlassian's **Personal Data Reporting** API, and Atlassian answers with the accounts that have been closed. Nothing else tells an app that a person left. Both stores are read and both are erased: in the key-value store a closed account's skill profile and the records keyed on it are removed, and in the audit table its rows are **deleted** — the row itself, not just the name on it, because an audit row carries an open metadata record about what happened.",
      "The app does not collect email addresses, passwords or payment data.",
    ],
    scopes: [
      "read:servicedesk-request",
      "read:jira-user",
      "read:jira-work",
      "write:jira-work",
      "storage:app",
      "report:personal-data",
    ],
    storageTech:
      "Forge app storage (key-value store) and Forge SQL, both hosted by Atlassian",
    external: ["`api.atlassian.com` — the Atlassian REST APIs of your own site and, for team routing, the Atlassian Teams API"],
  },

  {
    slug: "secret-scanner",
    name: "Secret Scanner for Jira",
    products: "Jira · Jira Service Management",
    icon: "/secret-scanner.png",
    summary:
      "Secret Scanner for Jira scans issue fields, comments, change history and text attachments for exposed credentials and PII — API keys, tokens, passwords, private keys and card numbers — and alerts administrators before the exposure spreads.",
    ai: false,
    persisted: [
      "**Findings** — for each detection: the issue key and summary, the field it was found in, the pattern and category that matched, the **masked** matched text (first four characters followed by asterisks), a SHA-256 hash of the raw match used only for deduplication, the detection timestamp, and — where the field is one somebody signs, a comment or a change history entry — the Atlassian account ID of its author.",
      "**Triage metadata** — the Jira issue created to track a leak and its status, plus dismissal records: who dismissed a finding, when, and the reason given.",
      "**Scanner configuration** — enabled categories and rules, your custom regex patterns, whether attachments and change history are scanned, auto-redaction and dismissal settings, project exclusions, and the target project and issue type for remediation tickets.",
      "**Audit log** — app events, retained for 90 days.",
      "**Scan job state** — progress and cursors for bulk scans, so a long scan can resume.",
    ],
    transient: [
      "issue summaries, descriptions, comments, custom field values and change history read during a scan",
      "text-based attachments up to 1 MB, read during a scan when attachment scanning is enabled",
      "field, project and user metadata needed to label a finding",
    ],
    personal: [
      "**The app never stores the credential it finds.** Only a masked preview (the first four characters) and a one-way SHA-256 hash of the raw match are written to storage. The hash cannot be reversed and exists solely to recognise the same finding twice.",
      "Because the app detects PII patterns — card numbers, national identifiers, contact details — a finding records that such a value was present in a specific field, in masked form only.",
      "**Atlassian account IDs are stored** where a finding or a triage action names a person: the author of a scanned comment or change, and the administrator who dismissed or resolved a finding. They are the identifiers Atlassian itself uses and are meaningless outside your tenant. **No display names or email addresses are stored** — a name shown in the app is fetched from Jira when the page is drawn.",
      "Once a day the app sends Atlassian the account IDs it holds, through Atlassian's **Personal Data Reporting** API, and Atlassian answers with the accounts that have been closed. Nothing else tells an app that a person left. When an account comes back as closed, its audit events are **deleted** — the row itself, not just the name on it, because an audit row carries an open metadata record about what happened — and its account ID is removed from the findings and dismissal records, which are kept: an exposed credential is still exposed, and a finding judged a false positive is still a false positive, once the person who wrote it has gone.",
      "Issue keys and issue summaries are stored so administrators can navigate to the affected issue.",
    ],
    scopes: [
      "read:jira-work",
      "write:jira-work",
      "read:jira-user",
      "storage:app",
      "report:personal-data",
    ],
    storageTech:
      "Forge app storage (key-value store) and Forge SQL, both hosted by Atlassian",
    external: [],
  },

  {
    slug: "workflow-toolkit",
    name: "Workflow Toolkit for Jira",
    products: "Jira · Jira Service Management",
    icon: "/workflow-toolkit.png",
    summary:
      "Workflow Toolkit for Jira adds AI-powered workflow modules — conditions, validators and post functions. You describe the rule in plain language and the app turns it into a check or an action that runs on the transition.",
    ai: true,
    aiData: [
      "the rule you wrote in plain language when configuring the condition, validator or post function",
      "the name, ID and type of the custom fields you selected under *Fields Involved*",
      "for a post function, a base context that is always sent: the issue's key, summary, full description text, status, priority, issue type, assignee, reporter, resolution, labels, components, fix versions, time tracking, parent, sprint, the transition being performed, the transitions currently available on the issue, its issue links, its sub-tasks with summary/status/assignee, and your site's issue link types",
      "for a post function, the context sources you enable on top of that: up to the 50 most recent change history entries, the 20 most recent comments, attachment metadata (name, MIME type, size, uploader and upload date — never file contents), and the custom fields you select together with their allowed values",
    ],
    persisted: [
      "**Audit events**, one row each: what ran, when, the issue key, the transition name, the counts of the actions taken, and — for a validator — the AI-written reason for its verdict. No account ID and no user name is stored on the row. Retained for **90 days**.",
      "**The generated expression and its AI-written title**, recorded each time you use *Generate Expression*.",
      "**Token usage** — the prompt, completion and total token counts of each AI call.",
      "Your **rule configuration** is *not* stored by the app. The rule description, rule text, generated expression, selected fields, context sources and enabled tools are stored by **Jira**, inside the workflow definition, exactly like the configuration of any built-in condition, and are covered by Atlassian's own data handling.",
    ],
    transient: [
      "the issue being transitioned: its field values, and — for a post function — its comments, change history, links, sub-tasks and available transitions, read at transition time",
      "workflow, transition, field and issue type metadata from Jira",
      "Jira is read with the app's own access rather than the acting user's",
    ],
    personal: [
      "Issue content is read to evaluate a rule or run a post function, and **no copy of the issue is retained**. An audit event does keep the validator's written reason for blocking a transition, which the AI derived from the issue — that is what answers \"why was this blocked?\" in the audit log.",
      "**No Atlassian account ID is stored.** An earlier version of this page said audit events recorded the account ID of whoever performed a transition. They never did — the column existed and nothing ever wrote to it — and it has been removed, so the statement is now true by construction rather than by intention. An audit event records what the app did on a transition, not who asked for it. One thing does still name people, stated plainly: a validator's written reason is prose the AI composed over the issue, and that context names people (assignee, reporter, comment authors, attachment uploaders) by display name, so a name can appear inside that sentence. It is a name in a sentence with no account attached, so it cannot be looked up or reported — what removes it is the 90-day retention deleting the row.",
      "Attachment **contents are never read**; only file metadata is included, and only when that context source is enabled.",
      "Atlassian's **Personal Data Reporting** cycle runs daily and currently reports nothing, because the app holds no account ID to report. The cycle is kept, and its erasure path with it: if the app ever stores an account ID again, a closed account's records are **deleted** — the whole record, not just the name on it, because the reason text on an audit event can describe the same person.",
      "The app does not collect email addresses, passwords, authentication tokens, API keys or payment data.",
    ],
    scopes: [
      "read:jira-work",
      "write:jira-work",
      "read:jira-user",
      "manage:jira-configuration",
      "send:notification:jira",
      "storage:app",
      "report:personal-data",
    ],
    storageTech:
      "Forge app storage (key-value store) and Forge SQL, both hosted by Atlassian",
    external: [],
  },

  {
    slug: "admin-toolkit",
    name: "Admin Toolkit for Jira",
    products: "Jira · Jira Service Management",
    icon: "/admin-toolkit.png",
    summary:
      "Admin Toolkit for Jira gives Jira administrators the tools Atlassian does not ship: bulk project management, custom field assessment and merging, scheme and filter cleanup, user mirroring, user analysis, offboarding, and post-migration cleanup.",
    ai: false,
    persisted: [
      "**Job state and results** — the progress, parameters and chunked results of the operations you run: custom field assessments, field merger analyses and the generated CSV rows, offboarding scans, scheme and filter scans, project activity scans and user analyses. Results are kept so you can review a completed run.",
      "**Tool configuration and preferences** — the settings of each tool, including the target project and issue type used when a tool creates an issue.",
    ],
    transient: [
      "project, field, screen, scheme, workflow, filter, board and permission configuration read from Jira",
      "issues affected by an operation you explicitly run",
      "user and group lookups from Jira",
      "the contents of the Atlassian Admin CSV files you upload to the User Analysis tool, which are parsed in memory to produce the analysis",
    ],
    personal: [
      "The results of the tools that work on people — a permission audit, an offboarding scan, a user analysis, a mirror operation — contain Atlassian account IDs, display names, email addresses (where the CSV you uploaded contains them) and group names, because that is the output you asked for. They are stored as part of the job result and removed when the job is reset or the app is uninstalled.",
      "CSV files uploaded to User Analysis are parsed to produce the analysis; the resulting aggregated report is stored, and the analysis is cleared when you start over.",
      "Once a day the app sends Atlassian the account IDs it holds, through Atlassian's **Personal Data Reporting** API, and Atlassian answers with the accounts that have been closed. Nothing else tells an app that a person left. When an account comes back as closed, the cycle walks the whole store and removes it: a record keyed on that person is deleted, and a record that merely names them has the name taken out.",
      "The app does not collect passwords, authentication tokens, API keys or payment data.",
    ],
    scopes: [
      "read:jira-work",
      "write:jira-work",
      "read:jira-user",
      "read:project:jira",
      "manage:jira-project",
      "manage:jira-configuration",
      "read:board-scope:jira-software",
      "read:board-scope.admin:jira-software",
      "storage:app",
      "report:personal-data",
    ],
    storageTech: "Forge app storage (key-value store)",
    external: ["`api.atlassian.com` — the Atlassian REST APIs of your own site"],
  },

  {
    slug: "custom-fields-toolkit",
    name: "Custom Fields Toolkit for Jira",
    products: "Jira · Jira Service Management",
    icon: "/cf-toolkit.png",
    summary:
      "Custom Fields Toolkit for Jira adds custom field types Jira does not offer natively — an Issue Picker driven by JQL, a Checklist with statuses and a transition validator, and a Masked Input with format validation — plus select list options that project administrators can manage themselves.",
    ai: false,
    persisted: [
      "**Field configuration** — the settings of each field context: the Issue Picker's JQL, display columns, quick filters and link behaviour; the Checklist's capabilities, custom statuses, validation mode and default items; the Masked Input's mask, character set, regex, algorithm and messages.",
      "**Select list delegation configuration** — which select fields, in which projects, project administrators are allowed to manage.",
    ],
    transient: [
      "issues and field values read to render a field or resolve an Issue Picker search",
      "project, field and context metadata from Jira",
      "user lookups from Jira, for checklist assignees and picker columns",
    ],
    personal: [
      "The values entered into the app's custom fields — selected issues, checklist items, masked text — are stored by **Jira** as ordinary custom field values on the issue, under Atlassian's own data handling, and follow the issue's permissions and lifecycle. The app also writes checklist metrics as a Jira issue property so they can be searched in JQL.",
      "The app's own storage holds configuration only. It does not store issue content, account identifiers, email addresses, passwords, authentication tokens, API keys or payment data.",
      "The Masked Input field hides its value in the user interface. Masking is a display and input-validation feature, not encryption of the underlying Jira field value.",
    ],
    scopes: ["read:jira-work", "write:jira-work", "read:jira-user", "manage:jira-configuration", "storage:app"],
    storageTech: "Forge app storage (key-value store)",
    external: [],
  },

  {
    slug: "license-waste-manager",
    name: "License Waste Manager for Jira",
    products: "Jira · JSM · Confluence · Jira Product Discovery",
    icon: "/license-waste.png",
    summary:
      "License Waste Manager for Jira identifies inactive and unnecessarily licensed users across your Atlassian products, visualises licence utilisation, automates deprovisioning through scheduled rules, and records every action in a compliance-ready audit log.",
    ai: false,
    persisted: [
      "**User snapshots** — for each account in scope: Atlassian account ID, display name, **email address** and email domain, active flag, account type, managed status, whether the account consumes a billable licence, last active date, the date the account was added to the organisation, product and product-access details, licence groups and avatar URL.",
      "**Group records** — group IDs, names and kinds, and which accounts belong to which group in a snapshot.",
      "**Automation rules** — the deprovisioning rules you define (criteria, action, schedule) and their run state.",
      "**Jobs** — scan and action jobs with type, status, phase, who requested them, timings, metrics and error messages.",
      "**Audit log** — every action the app performed: what was done, by which rule or administrator, when, and the per-user outcome (account ID, display name, success or failure, error message).",
      "**Configuration** — the inactivity threshold, protected users, groups and domains, detected licence groups, and the **organisation ID and organisation API key** you supply. The key is masked in the interface.",
    ],
    transient: [
      "user, group and product access data read from the Atlassian user management and admin APIs of your own organisation",
      "activity data used to decide whether an account is inactive",
    ],
    personal: [
      "This app is about user accounts, so it necessarily processes personal data: **account IDs, display names, email addresses, avatar URLs, group membership, product access and last activity dates** are stored in the snapshots and in the audit log.",
      "That data is stored only inside your own Atlassian tenant and is used exclusively to show licence utilisation, evaluate your rules and provide an audit trail of the actions taken.",
      "The **organisation API key** is a credential you provide. It grants organisation-admin level access, is stored inside your own tenant, is masked in the interface, and can be removed at any time with **Disconnect**.",
      "Snapshots are replaced by newer scans and can be deleted from the app. Audit records — the entry and its per-user detail together — are kept for **90 days** and then deleted automatically, so a record is either fully answerable or gone; you can also delete them yourself, and uninstalling erases them.",
      "Once a day the app sends Atlassian the account IDs it holds, through Atlassian's **Personal Data Reporting** API, and Atlassian answers with the accounts that have been closed. Nothing else tells an app that a person left. A closed account's snapshot rows — the account, its group memberships and its product access — and its per-user audit detail are **deleted**. The audit entry itself survives without them: what ran, when, by which rule and how many accounts it affected, which is what the trail is for.",
      "The app does not collect passwords or payment data.",
    ],
    scopes: [
      "read:jira-user",
      "read:jira-work",
      "storage:app",
      "report:personal-data",
    ],
    storageTech: "Forge app storage (key-value store) and Forge SQL, both hosted by Atlassian",
    external: ["`api.atlassian.com` — the Atlassian REST APIs of your own site and the Atlassian organisation admin API"],
  },

  {
    slug: "markdown-toolkit",
    name: "Markdown Toolkit for Confluence",
    products: "Confluence",
    icon: "/markdown-toolkit.png",
    summary:
      "Markdown Toolkit for Confluence exports Confluence content as Markdown — single pages, page trees or entire spaces — and provides an in-page macro that renders Markdown with code highlighting, Mermaid diagrams and math expressions. It holds no write permission and creates no content in Confluence.",
    ai: false,
    persisted: [
      "**Macro content** — the Markdown you type into a Markdown macro, stored per macro instance so the macro can render it.",
      "**Export jobs** — a manifest of what a job covers and the converted page content held in chunks while the job runs and until you download, reset or discard it.",
    ],
    transient: [
      "page and space content, titles, labels and attachments read from Confluence during an export",
      "space and page metadata needed to name the files and rebuild the hierarchy",
    ],
    personal: [
      "An export processes the content you select. During a job, that content — including any personal data your pages happen to contain — is held in app storage inside your tenant until the job finishes and its data is cleared.",
      "Macro content is stored as written by the page author.",
      "Your Atlassian account ID is stored while an export runs, as the key that keeps your job separate from anyone else's. The record is removed when the job is cleared. The app does not collect email addresses, display names, passwords, authentication tokens, API keys or payment data.",
      "Once a day the app sends Atlassian the account ID on each job record it holds, through Atlassian's **Personal Data Reporting** API, and Atlassian answers with the accounts that have been closed. Nothing else tells an app that a person left. A closed account's job records are deleted, and the account ID on a job record is the only thing about that person the app has to clean up.",
    ],
    scopes: [
      "read:confluence-content.all",
      "read:confluence-content.summary",
      "read:space:confluence",
      "read:page:confluence",
      "storage:app",
      "report:personal-data",
    ],
    storageTech: "Forge app storage (key-value store)",
    external: [],
  },
];

export function findPrivacy(slug: string): PrivacyFacts | undefined {
  return PRIVACY_FACTS.find((p) => p.slug === slug);
}
